### ISSUE TITLE
Support redis

### ISSUE THREAD

**Issue by QuentinN42** [grafana/pdc-agent#65]
Hello,
Thanks for this insane component !

I'm currently moving some part of the monitoring to grafana to have automatic alerting and some people in my company are using redis.

After looking into the documentation, I don't see redis.

Does the support must be done in this repo or in another one ?

https://grafana.com/docs/grafana-cloud/connect-externally-hosted/private-data-source-connect/#pdc-known-limitations

**Comment by dafydd-t** [comment]
Hi! Thanks for your interest.

 I would suggest opening an issue on https://github.com/RedisGrafana/grafana-redis-datasource because the redis datasource is not owned by Grafana. We have reached out to the RedisGrafana team in [this issue](https://github.com/RedisGrafana/grafana-redis-datasource/issues/118), maybe if you comment there we could make some progress.
